### ISSUE TITLE
Segfault when building on Mac with M1

### ISSUE THREAD

**Issue by PikalaxALT** [pret/agbcc#43]
Segfault seems to be specific to Macs with M1 
Tried to ./build.sh on three differents macs running Big Sur 11.4, had no success with the M1 one (segfault 11)

_Originally posted by @TGFbSMAD in https://github.com/pret/agbcc/issues/38#issuecomment-875438895_

**Comment by PikalaxALT** [comment]
@TGFbSMAD please reply to this issue with additional details. What does the script try to do immediately before the segfault?

**Comment by TGFbSMAD** [comment]
Where it start : 
<img width="564" alt="Capture d’écran 2021-07-07 à 14 06 30" src="https://user-images.githubusercontent.com/61919552/124756599-e8aae100-df2c-11eb-8c95-4d49c775d920.png">

End of the script : 
<img width="564" alt="Capture d’écran 2021-07-07 à 14 06 05" src="https://user-images.githubusercontent.com/61919552/124756610-ee082b80-df2c-11eb-9588-b4876df75701.png">

Using the agbcc from https://github.com/pizza2004/agbcc

**Comment by ScottNortonPhD** [comment]
It seems you're using a different, third-party fork of agbcc. Could you verify please that the same issue occurs on this fork as well?

**Comment by TGFbSMAD** [comment]
Using the pret abcc leads to another error which has been fixed by pizza2004’s fork.
I think that the same error would occure if the fix was applied here.

**Comment by Manurocker95** [comment]
So... still no fix for M1? :(

**Comment by PikalaxALT** [comment]
> So... still no fix for M1? :(

We would need for one of the devs to obtain an M1 Mac before work can begin on this. As such, there is no timeline to fix this.

**Comment by Manurocker95** [comment]
> > So... still no fix for M1? :(
> 
> We would need for one of the devs to obtain an M1 Mac before work can begin on this. As such, there is no timeline to fix this.

Do you know if there was any new about this?

**Comment by luckytyphlosion** [comment]
This actually might have been resolved, according to a post made by pfero in the Discord:
> Update on M1 support: Turns out it was a confusion with different components being installed under rosetta and not. Please make sure to install everything under rosetta, including devkitpro and homebrew+libpng (which should be installed in /usr/local, not /opt/homebrew). Building natively/without rosetta isn't properly supported yet, more info if you'd like to help can be found at: https://discord.com/channels/442462691542695948/442465020291317760/897562585195499620
You'll need to join the Discord to view that link.

**Comment by tkolarik** [comment]
I am still having the same issue, How can I ensure I am installing everything under rosetta?

**Comment by tkolarik** [comment]
Following these steps and installing libpng under rosetta fixed it for me https://indiespark.top/software/run-command-line-apple-silicon/

**Comment by hgmich** [comment]
There's confirmation that the changes in the above PR (#52) resolve this issue.

**Comment by poke-wally-world** [comment]
In attempting to build pokeemerald, I'm still encountering the same segfault error as OP despite using the new version of agbcc.

**Comment by poke-wally-world** [comment]
> In attempting to build pokeemerald, I'm still encountering the same segfault error as OP despite using the new version of agbcc.

Apologies -- I didn't realize that master didn't contain PR #52. After checking out that branch specifically, the build works on my machine with an M1 chip -- thanks again!

**Comment by thomason-jesse** [comment]
Additional confirmation that the referenced PR (#52) resolves this issue; just came here with it and found this solution. Seems like it's not merged into main yet
